# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jira < Formula
  desc "Command-line interface for Jira Cloud"
  homepage "https://github.com/mjumelet/jira-cli"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mjumelet/jira-cli/releases/download/v0.4.1/jira-cli_0.4.1_darwin_amd64.tar.gz"
      sha256 "72056205c1c9e7c053118c6f501b7d93c36912cde9bedb4008d5a1ec259536fc"

      define_method(:install) do
        bin.install "jira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mjumelet/jira-cli/releases/download/v0.4.1/jira-cli_0.4.1_darwin_arm64.tar.gz"
      sha256 "e2da66162dc5df559a8ca2abcd7ed029e33c9eabc431a5a3056bf9cf006fa31f"

      define_method(:install) do
        bin.install "jira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mjumelet/jira-cli/releases/download/v0.4.1/jira-cli_0.4.1_linux_amd64.tar.gz"
      sha256 "f2ac544c85b5fbf205874a7fc7520672887f49d51e75c8ef4ca3d25bf897c66b"
      define_method(:install) do
        bin.install "jira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mjumelet/jira-cli/releases/download/v0.4.1/jira-cli_0.4.1_linux_arm64.tar.gz"
      sha256 "3b812cb2cbd02599501d22226ba9c3e5362e461c8b43bc64c29db9638e0f1c91"
      define_method(:install) do
        bin.install "jira"
      end
    end
  end

  test do
    system "#{bin}/jira", "--version"
  end
end
