# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jira < Formula
  desc "Command-line interface for Jira Cloud"
  homepage "https://github.com/mjumelet/jira-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mjumelet/jira-cli/releases/download/v0.2.0/jira-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "3cd454d0158de985f2ece6600c2eb48d1014b04be8daeb8c386ab89fe27d0f96"

      define_method(:install) do
        bin.install "jira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mjumelet/jira-cli/releases/download/v0.2.0/jira-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "d92becbec5d09981b8547a7ad164803a4ef96957325edbb07a25ff80fe5297b1"

      define_method(:install) do
        bin.install "jira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mjumelet/jira-cli/releases/download/v0.2.0/jira-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "9b8033e7747c2dbc86d6948f7523da8aeb988030c27e519657ef6f4840ebd6d5"
      define_method(:install) do
        bin.install "jira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mjumelet/jira-cli/releases/download/v0.2.0/jira-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "9fd1dc4e69e8309dc46dfe42d7e18c539d82cc816f15d4ecff03578b56cc28f9"
      define_method(:install) do
        bin.install "jira"
      end
    end
  end

  test do
    system "#{bin}/jira", "--version"
  end
end
